### PR TITLE
Update PBR example to gltf version 0.9

### PR DESCRIPTION
**Pull request by alteous**
As per title.

### CODE REVIEW

**Comment by vitvakatu** [comment]
Where is Travis?

**Comment by alteous** [comment]
Huh?!

**Comment by vitvakatu** [comment]
@alteous it seems like we lost our CI after translating repository. There is no tests before merge anymore

**Comment by alteous** [comment]
Oh, that's weird. :worried: 

Maybe @kvark will be able to diagnose the issue?

**Comment by kvark** [comment]
Trying to restart travis.

**Pull request merged**
